[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; script-src https://ashmortar.io"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"