[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; img-src https:; script-src 'self'; style-src 'self'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self 'https://ashmortar.io)"
[[plugins]]
  [plugins.inputs]
  template = "hierarchical"
  branches = ['main', 'feature/algolia']